### ISSUE TITLE
Error - Installing django-city-limits using pipenv

### ISSUE THREAD

**Issue by jdhillen** [LegoStormtroopr/django-limits#3]
I found your library and was going to test it out. But I got an error while installing it using pipenv.

```
Installing django-city-limits...
Collecting django-city-limits

Error:  An error occurred while installing django-city-limits!
Could not find a version that satisfies the requirement django-city-limits (from versions: )
No matching distribution found for django-city-limits
```

I'm using Python 3.6.4 on a Mac. Any help would be greatly appreciated.

Thanks!

**Comment by jdhillen** [comment]
Update - I was able to install it by using `pipenv install django-limits` instead of `pipenv install django-city-limits`

**Comment by LegoStormtroopr** [comment]
Hi @jdhillen thanks for bringing this up, I'll get the documentation fixed asap.
